version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "ci/setup"
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "alecpos"
    reviewers:
      - "alecpos"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "alecpos"
    assignees:
      - "alecpos"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "ci/setup"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "alecpos"
    reviewers:
      - "alecpos"
