version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "alecposner53859"
    assignees:
      - "alecposner53859"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] 